USE [master]
GO
/****** Object:  Database [Users_Profile]    Script Date: 2018/10/23 12:43:48 ******/
CREATE DATABASE [Users_Profile]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Users_Profile', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Users_Profile.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Users_Profile_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Users_Profile_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Users_Profile] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Users_Profile].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Users_Profile] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Users_Profile] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Users_Profile] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Users_Profile] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Users_Profile] SET ARITHABORT OFF 
GO
ALTER DATABASE [Users_Profile] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Users_Profile] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Users_Profile] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Users_Profile] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Users_Profile] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Users_Profile] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Users_Profile] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Users_Profile] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Users_Profile] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Users_Profile] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Users_Profile] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Users_Profile] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Users_Profile] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Users_Profile] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Users_Profile] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Users_Profile] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Users_Profile] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Users_Profile] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Users_Profile] SET  MULTI_USER 
GO
ALTER DATABASE [Users_Profile] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Users_Profile] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Users_Profile] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Users_Profile] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Users_Profile] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Users_Profile] SET QUERY_STORE = OFF
GO
USE [Users_Profile]
GO
/****** Object:  Table [dbo].[Users_Account]    Script Date: 2018/10/23 12:43:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users_Account](
	[user_id] [int] NOT NULL,
	[user_account] [nchar](10) NULL,
	[user_password] [nchar](10) NULL,
 CONSTRAINT [PK_Users_Account] PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Users_Profile] SET  READ_WRITE 
GO
